### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by StrangerMersault** [etc5had0w/penbud#1]
```
Traceback (most recent call last):
  File "C:\Users\***\Documents\Program\python\penbud\penbud\penbud.py", line 357, in <module>
    toolcheck()
  File "C:\Users\***\Documents\Program\python\penbud\penbud\penbud.py", line 54, in toolcheck
    output = subprocess.call(["which", i], stdout=NOECHO, stderr=subprocess.STDOUT)
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

Steps to reproduce using W10 cmd.exe:
1) git clone Penbud
2) Open penbud.py
3) FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by etc5had0w** [comment]
Tool is made for linux with python3 so please meet the requirements to run the tool.

More specifically kali linux is recommended.
